small amt mul gcn update
thesis20/thesis_paper pull request #11
Opened 2021-05-21 11:49 UTC by Eduardsen

2021-05-21 11:51 UTC, andpaacoke commented on sections/problem/problem-chapter.tex
> +The adjacency matrix is useful for implementation of a graph convolutional layer as it allows us to implement graph convolution through matrix multiplication between the adjacency matrix and the repr
Skal vi også nævne her hvordan vi normaliserer med degree matrix'en?

2021-05-21 11:57 UTC, andpaacoke approved these changes

2021-05-21 12:57 UTC, Moesgaarda requested changes

2021-05-21 12:57 UTC, Moesgaarda commented on sections/problem/problem-chapter.tex
> +Finally, a degree matrix can be employed in order to normalize the representations by the number of neighbors.
måske skrive hvordan en degree matrix ser ud? det kommenterede manfred på

2021-05-21 12:57 UTC, Moesgaarda commented on sections/problem/problem-chapter.tex
> +Finally, a degree matrix can be employed in order to normalize the representations by the number of neighbors.
```suggestion
Finally, a degree matrix consisting of the summation of row entries in the diagonal can be employed in order to normalize the representations by the number of neighbors.
```

2021-05-24 08:10 UTC, Moesgaarda approved these changes

2021-05-24 10:03 UTC, andpaacoke approved these changes

2021-05-24 10:03 UTC, merged