conc me
thesis20/thesis_paper pull request #52
Opened 2021-05-28 08:36 UTC by Eduardsen

2021-05-28 09:20 UTC, andpaacoke requested changes

2021-05-28 09:20 UTC, andpaacoke commented on sections/conclusion/conclusion-chapter.tex
> +On the Frappe dataset the CSGCN models are outperformed by $84.45\%$ to $-1473.37\%$.
```suggestion
On the Frappe dataset the CSGCN models are outperformed by $-84.45\%$ to $-1473.37\%$.
```
er det ikke intended at det er -84.45?

2021-05-28 09:24 UTC, Eduardsen commented on sections/conclusion/conclusion-chapter.tex
> +On the Frappe dataset the CSGCN models are outperformed by $84.45\%$ to $-1473.37\%$.
er det ikke weird at sige de bliver otuperformed med -x %? sad og overvejede det da jeg skrev det pogså 🤔

2021-05-28 09:26 UTC, Moesgaarda commented on sections/conclusion/conclusion-chapter.tex
> +On the Frappe dataset the CSGCN models are outperformed by $84.45\%$ to $-1473.37\%$.
det skal 100p være uden minus

2021-05-28 09:28 UTC, andpaacoke commented on sections/conclusion/conclusion-chapter.tex
> +On the Frappe dataset the CSGCN models are outperformed by $84.45\%$ to $-1473.37\%$.
Hvorfor står der så minus ved det andet tal?

2021-05-28 09:34 UTC, Eduardsen commented on sections/conclusion/conclusion-chapter.tex
> +On the Frappe dataset the CSGCN models are outperformed by $84.45\%$ to $-1473.37\%$.
xd
det er mig der kombinerer dem

2021-05-28 09:53 UTC, andpaacoke approved these changes

2021-05-30 17:47 UTC, Moesgaarda approved these changes

2021-06-03 07:21 UTC, merged