description of uc and ic and stuff
thesis20/thesis_paper pull request #8
Opened 2021-05-21 09:27 UTC by andpaacoke

2021-05-21 10:14 UTC, Eduardsen commented on sections/csgcn/csgcn-chapter.tex
> +Additionally, we add the identity matrix $I$ to the last quadrant so that for each convolution, the context embeddings are only propagated with information about themselves.
```suggestion
Additionally, we add the identity matrix $I$ to the last quadrant such that the context embeddings are only propagated with information about themselves in each convolution.
```

2021-05-21 10:15 UTC, Eduardsen commented on sections/csgcn/csgcn-chapter.tex
> +We found that for this version of the model, it gave slightly better performance compared to multipluying with $D^{\frac{1}{2}}$ on both sides of the adjacency matrix.
```suggestion
We found that for this version of the model, it gave slightly better performance compared to multiplying by $D^{\frac{1}{2}}$ on both sides of the adjacency matrix.
```

2021-05-21 10:15 UTC, Eduardsen commented on sections/csgcn/csgcn-chapter.tex
> +The final embedding matrix after $l$ layers is obtained in the same way as CSGCN-IS where we take the mean of the nodes' representation at each layer.
```suggestion
The final embedding matrix after $l$ layers is obtained in the same way as CSGCN-IS where we take the mean of the nodes' representations at each layer.
```

2021-05-21 13:11 UTC, Moesgaarda requested changes

2021-05-21 13:11 UTC, Moesgaarda commented on sections/csgcn/csgcn-chapter.tex
> +Additionally, we add the identity matrix $I$ to the last quadrant such that the context embeddings are only propagated with information about themselves in each convolution.
```suggestion
Instead, we add the identity matrix $I$ to the last quadrant such that the context embeddings are only propagated with information about themselves in each convolution.
```

2021-05-21 13:11 UTC, Moesgaarda commented on sections/csgcn/csgcn-chapter.tex
> +The final embedding matrix after $l$ layers is obtained in the same way as CSGCN-IS where we take the mean of the nodes' representations at each layer.
men har vi faktisk kørt extensive forsøg med at erstatte med random walk og på begge sider?

2021-05-24 07:12 UTC, andpaacoke commented on sections/csgcn/csgcn-chapter.tex
> +The final embedding matrix after $l$ layers is obtained in the same way as CSGCN-IS where we take the mean of the nodes' representations at each layer.
Men hvordan kan vi så forklare at vi gør det?

2021-05-24 07:51 UTC, Eduardsen commented on sections/csgcn/csgcn-chapter.tex
> +We found that for this version of the model, it gave slightly better performance compared to multiplying by $D^{\frac{1}{2}}$ on both sides of the adjacency matrix.
skal vi name droppe at det er den der random walk laplacian?

2021-05-24 10:02 UTC, Moesgaarda approved these changes

2021-05-24 10:02 UTC, Eduardsen approved these changes

2021-05-24 10:03 UTC, merged