adam and ham der gradient
thesis20/thesis_paper pull request #9
Opened 2021-05-21 10:06 UTC by Eduardsen

2021-05-21 13:06 UTC, Moesgaarda commented on sections/csgcn/csgcn-chapter.tex
> +For a specific model parameter, this is done by calculating the gradient of the loss function at each iteration with respect to the model parameter, and then updating it according to the gradient usi
using a learning rate lyder lidt spøjst gør det ikke?
er learning rate ikke i bund og grund bare stepsize (hvor langt den tør hoppe pr update?)

2021-05-21 13:10 UTC, Moesgaarda requested changes

2021-05-21 13:10 UTC, Moesgaarda commented on sections/csgcn/csgcn-chapter.tex
> +The chosen optimizer  can impact the training speed and final performance of the model.
```suggestion
The chosen optimizer can impact the training speed and final performance of the model.
```

2021-05-24 07:48 UTC, Eduardsen commented on sections/csgcn/csgcn-chapter.tex
> +For a specific model parameter, this is done by calculating the gradient of the loss function at each iteration with respect to the model parameter, and then updating it according to the gradient usi
jo, så den bruger learning raten til at bestemme størrelsen af updaten?

2021-05-24 08:09 UTC, Moesgaarda approved these changes

2021-05-24 10:05 UTC, andpaacoke approved these changes

2021-05-24 10:05 UTC, merged